// 为每个游戏分类定义独特的颜色组合
export const categoryColors: Record<string, { bg: string; text: string }> = {
    '热门': { bg: 'bg-red-100', text: 'text-red-700' },
    '经典': { bg: 'bg-blue-100', text: 'text-blue-700' },
    '益智': { bg: 'bg-green-100', text: 'text-green-700' },
    '街机': { bg: 'bg-yellow-100', text: 'text-yellow-700' },
    '休闲': { bg: 'bg-pink-100', text: 'text-pink-700' },
    '动作': { bg: 'bg-orange-100', text: 'text-orange-700' },
    '射击': { bg: 'bg-purple-100', text: 'text-purple-700' },
    '解谜': { bg: 'bg-indigo-100', text: 'text-indigo-700' },
    '策略': { bg: 'bg-teal-100', text: 'text-teal-700' },
    '冒险': { bg: 'bg-cyan-100', text: 'text-cyan-700' },
    '放置': { bg: 'bg-lime-100', text: 'text-lime-700' },
    '创新': { bg: 'bg-amber-100', text: 'text-amber-700' },
    '竞速': { bg: 'bg-rose-100', text: 'text-rose-700' },
    '体育': { bg: 'bg-emerald-100', text: 'text-emerald-700' },
    '文字': { bg: 'bg-violet-100', text: 'text-violet-700' },
    '沙盒': { bg: 'bg-fuchsia-100', text: 'text-fuchsia-700' },
    '音乐': { bg: 'bg-sky-100', text: 'text-sky-700' },
    '跑酷': { bg: 'bg-orange-100', text: 'text-orange-700' },
    '科学': { bg: 'bg-blue-100', text: 'text-blue-700' },
    '3D': { bg: 'bg-purple-100', text: 'text-purple-700' },
    '复古': { bg: 'bg-amber-100', text: 'text-amber-700' },
    '生存': { bg: 'bg-red-100', text: 'text-red-700' },
    '科幻': { bg: 'bg-indigo-100', text: 'text-indigo-700' },
    '艺术': { bg: 'bg-pink-100', text: 'text-pink-700' },
    '工业': { bg: 'bg-gray-100', text: 'text-gray-700' },
    '格斗': { bg: 'bg-red-100', text: 'text-red-700' },
    '极简': { bg: 'bg-slate-100', text: 'text-slate-700' },
    '恐怖': { bg: 'bg-stone-100', text: 'text-stone-700' },
    '管理': { bg: 'bg-teal-100', text: 'text-teal-700' },
    '模拟': { bg: 'bg-cyan-100', text: 'text-cyan-700' },
    '迷宫': { bg: 'bg-emerald-100', text: 'text-emerald-700' },
    '黑客': { bg: 'bg-violet-100', text: 'text-violet-700' }
};